name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Add safe directory exception
        run: git config --global --add safe.directory D:/actions-runner/_work/Kursach_2024/Kursach_2024

      - name: Test
        run: echo "Testing ..."

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop and remove previous container
        run:  |
          $containers = docker ps -a -q
          if ($containers) {
            docker rm -f $containers
          } else {
            Write-Output "No containers available for cleaning"
          }

      - name: Build the Docker image
        run: docker build -t obraz:first .

      - name: Deploy the Docker image
        run: docker run -d -p 80:80 obraz:first
